export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpeg",
      username: "Azadeh Ghobadi",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpeg",
      username: "Bahar Ahmadi",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpeg",
      username: "Alexus Riki",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Dr Shabnam",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Azi joon",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: "ozra khanoom",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Abi joon",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Sayeh Hami",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "Bidi Heydari",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Dario HH",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Giza Necropolis ",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/2.jpeg",
      date: "10 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Jolfa church in Tbriz",
      photo: "assets/post/3.jpeg",
      date: "45 mins ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4.jpeg",
      date: "1 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5.jpeg",
      date: "2 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Naghshe Rostam Rock Relif",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Kashan ",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];